def convolution_998244353(a: list[int], b: list[int]) -> list[int]: ...
def convolution_1000000007(a: list[int], b: list[int]) -> list[int]: ...
def convolution_ll(a: list[int], b: list[int]) -> list[int]: ...
