def pow_mod(x: int, n: int, m: int) -> int: ...
def inv_mod(x: int, m: int) -> int: ...
def crt(r: list[int], m: list[int]) -> tuple[int, int]: ...
def floor_sum(n: int, m: int, a: int, b: int) -> int: ...
