from typing import overload

class mcf_graph:
    def __init__(self, n: int = 0) -> None: ...
    def add_edge(self, from_: int, to: int, cap: int, cost: int) -> int: ...

    class edge:
        from_: int
        to: int
        cap: int
        flow: int
        cost: int
    def get_edge(self, i: int) -> edge: ...
    def edges(self) -> list[edge]: ...
    @overload
    def flow(self, s: int, t: int) -> tuple[int, int]: ...
    @overload
    def flow(self, s: int, t: int, flow_limit: int) -> tuple[int, int]: ...
    @overload
    def slope(self, s: int, t: int) -> list[tuple[int, int]]: ...
    @overload
    def slope(self, s: int, t: int, flow_limit: int) -> list[tuple[int, int]]: ...
