from typing import Callable, Generic, TypeVar, overload

S = TypeVar("S")

class segtree(Generic[S]):
    @overload
    def __init__(
        self,
        op: Callable[[S, S], S],
        e: Callable[[], S],
        n: int = 0,
    ) -> None: ...
    @overload
    def __init__(
        self,
        op: Callable[[S, S], S],
        e: Callable[[], S],
        v: list[int],
    ) -> None: ...
    def set(self, p: int, x: S) -> None: ...
    def get(self, p: int) -> S: ...
    def prod(self, l: int, r: int) -> S: ...
    def all_prod(self) -> S: ...
    def max_right(self, l: int, g: Callable[[S], bool]) -> int: ...
    def min_left(self, r: int, g: Callable[[S], bool]) -> int: ...
